import {
    MachineManagementIcon,
    MachineListIcon,
    MachineAnalyticsIcon,
    ConfigIcon,
    MachineUpdateIcon,
    MachineWarningIcon,
    MachineHistoryIcon,
    CameraManagementIcon,
    CameraLogIcon,
    TransactionListIcon,
    UserManagementIcon,
    UserManagementListIcon,
    GroupPolicyIcon,
    UnitManagementIcon,
    DisplayManagementIcon,
    ScreenDisplayIcon,
    DisplayManagementStorageIcon,
} from "@/assets";

export const icons = {
    "machine-management": MachineManagementIcon,
    "machine-list": MachineListIcon,
    "machine-stats": MachineAnalyticsIcon,
    "machine-config": ConfigIcon,
    "machine-update": MachineUpdateIcon,
    "machine-warning": MachineWarningIcon,
    "machine-history": MachineHistoryIcon,
    "camera-management": CameraManagementIcon,
    "camera-log": CameraLogIcon,
    "transaction-list": TransactionListIcon,
    "user-management": UserManagementIcon,
    "user-list": UserManagementListIcon,
    "group-policy": GroupPolicyIcon,
    "management-unit": UnitManagementIcon,
    "display-management": DisplayManagementIcon,
    "screen-display": ScreenDisplayIcon,
    "display-storage": DisplayManagementStorageIcon,
};
